"""
demos/multi-arch-30/tests/test_multi_arch_30.py

R110-53: Tests for the multi-arch-30 DEMO live IN the demo folder
(per user rule: "tests of demos belong in the demo folder").

R110-53b: demos/ is FULLY AUTONOMOUS — zero imports from tests/.
The classify_domain helper is vendored in _helpers.py (intentional
DRY violation, kept in sync manually). The demos/ tree is a closed
unit: it can be copied out of the mas-engineer repo and still work.

The 7 tests validate:
  R110-41 (4 tests): multi-arch-30 master orchestrator consistency
    - master.yaml exists
    - master declares >= 6 sub_recipes
    - every sub_recipe.path resolves
    - every teams/*.yaml classifies as "demo-team"
  R110-42 (3 tests): e2e-results wrappers (generated by R110-28
    team-composition runs of the multi-arch-30 orchestrator)
    - e2e-results/ exists
    - contains >= 1 yaml file
    - every yaml parses to a dict
"""
from pathlib import Path

import yaml

# Resolve all paths relative to this file. No sys.path manipulation,
# no imports from tests/. demos/ is autonomous.
TESTS_DIR = Path(__file__).resolve().parent
DEMO_DIR = TESTS_DIR.parent                      # demos/multi-arch-30/
REPO_ROOT = DEMO_DIR.parent.parent               # repo root (parents[2] from tests/)

MULTI_ARCH_DIR = DEMO_DIR
MULTI_ARCH_MASTER = MULTI_ARCH_DIR / "multi-arch-30.yaml"
MULTI_ARCH_TEAMS_DIR = MULTI_ARCH_DIR / "teams"
E2E_RESULTS_DIR = REPO_ROOT / "e2e-results"

# classify_domain lives next to this test file (demos/multi-arch-30/tests/_helpers.py).
# pytest adds the test's parent dir to sys.path automatically (rootdir conftest),
# so a plain `import _helpers` works without making demos/ a package
# (and thus avoids the "tests.test_multi_arch_30" namespace conflict with
# the central tests/ directory that contains its own __init__.py).
import _helpers  # noqa: E402
classify_domain = _helpers.classify_domain


# ---- R110-41: multi-arch-30 master orchestrator consistency ----

def test_multi_arch_30_master_exists():
    """multi-arch-30.yaml must exist (master orchestrator)."""
    assert MULTI_ARCH_MASTER.exists(), (
        f"Missing: {MULTI_ARCH_MASTER}. R110-30 multi-architecture registry."
    )


def test_multi_arch_30_master_has_sub_recipes():
    """Master orchestrator must declare >= 6 sub_recipes (one per team)."""
    if not MULTI_ARCH_MASTER.exists():
        return
    with open(MULTI_ARCH_MASTER) as f:
        data = yaml.safe_load(f)
    assert data is not None, f"{MULTI_ARCH_MASTER} is empty or invalid YAML"
    sub_recipes = data.get("sub_recipes", [])
    assert len(sub_recipes) >= 6, (
        f"{MULTI_ARCH_MASTER} declares {len(sub_recipes)} sub_recipes, expected 6+ "
        f"(code-review, security-scan, data-quality, perf-eval, refactor, doc-gen)"
    )


def test_multi_arch_30_all_sub_recipe_paths_resolve():
    """Every sub_recipe.path in master must point to an existing file."""
    if not MULTI_ARCH_MASTER.exists():
        return
    with open(MULTI_ARCH_MASTER) as f:
        data = yaml.safe_load(f)
    if data is None:
        return
    missing = []
    for sub in data.get("sub_recipes", []):
        rel = sub.get("path", "")
        if rel.startswith("./"):
            abs_path = (MULTI_ARCH_DIR / rel[2:]).resolve()
        else:
            abs_path = (MULTI_ARCH_DIR / rel).resolve()
        if not abs_path.exists():
            missing.append(str(sub.get("name", "?")) + " -> " + rel)
    assert not missing, (
        f"R110-41: {len(missing)} sub_recipe paths in {MULTI_ARCH_MASTER.name} "
        f"are broken. Missing: {missing}"
    )


def test_multi_arch_30_team_recipes_classified():
    """Every recipe under multi-arch-30/teams/ is classified as 'demo-team'."""
    if not MULTI_ARCH_TEAMS_DIR.exists():
        return
    out = {}
    for p in MULTI_ARCH_TEAMS_DIR.glob("*.yaml"):
        try:
            with open(p) as f:
                data = yaml.safe_load(f)
        except Exception:
            continue
        if isinstance(data, dict):
            out[p.name] = classify_domain(p.name, data, parent_path=p.parent)
    wrong = {k: v for k, v in out.items() if v != "demo-team"}
    assert not wrong, (
        f"R110-41: {len(wrong)}/{len(out)} multi-arch-30/teams/* recipes "
        f"are NOT classified as 'demo-team' (path-based classification broken). "
        f"Wrong: {wrong}"
    )


# ---- R110-42: e2e-results wrappers (generated by R110-28 team-composition) ----

def test_e2e_results_directory_exists():
    """e2e-results/ must exist (generated by R110-28 team-composition)."""
    assert E2E_RESULTS_DIR.exists(), (
        f"Missing: {E2E_RESULTS_DIR}. R110-42 — e2e-results from team-composition runs."
    )


def test_e2e_results_have_yaml_files():
    """e2e-results must contain at least one .yaml file (sanity)."""
    if not E2E_RESULTS_DIR.exists():
        return
    yamls = list(E2E_RESULTS_DIR.rglob("*.yaml"))
    assert len(yamls) > 0, (
        f"R110-42: {E2E_RESULTS_DIR} has no .yaml files. "
        f"Expected team-composition wrappers."
    )


def test_e2e_results_wrappers_valid_yaml():
    """Every e2e-results wrapper file must be valid YAML (parses to a dict)."""
    if not E2E_RESULTS_DIR.exists():
        return
    bad = []
    for p in E2E_RESULTS_DIR.rglob("*.yaml"):
        try:
            with open(p) as f:
                data = yaml.safe_load(f)
            if not isinstance(data, dict):
                bad.append((str(p), "not a dict"))
        except Exception as e:
            bad.append((str(p), str(e)[:50]))
    assert not bad, (
        f"R110-42: {len(bad)} e2e-results yaml files are invalid. "
        f"First 5: {bad[:5]}"
    )
