"""
demos/multi-arch-30/tests/test_multi_arch_30.py

R110-53: Tests for the multi-arch-30 DEMO live IN the demo folder
(per user rule: "tests of demos belong in the demo folder").

These tests validate the multi-arch-30 orchestrator recipe + its
generated team/sub-recipes, plus the R110-42 e2e-results wrappers
(generated by R110-28 team-composition runs).

The tests are imported by pytest via default rootdir collection
(no pytest.ini needed — pytest finds test_*.py anywhere under the
repo root by default).

Imports the constants + classify_domain helper from
tests/test_recipe_registry_consistency.py to avoid duplicating
the DOMAIN-classification logic.
"""
import sys
from pathlib import Path

import pytest
import yaml

# Add repo root to sys.path so we can import from tests/
# (the demo test lives at demos/multi-arch-30/tests/, so
# `from tests.X import Y` requires the repo root on sys.path)
REPO_ROOT = Path(__file__).resolve().parents[2]  # demos/multi-arch-30/tests/ -> repo root is 2 levels up from tests/ = 3 levels up from file
# Actually: file is demos/multi-arch-30/tests/test_multi_arch_30.py
#   parents[0] = demos/multi-arch-30/tests/
#   parents[1] = demos/multi-arch-30/
#   parents[2] = demos/                  <-- this is what we want as "repo root for import"
# But the REAL repo root is parents[3] = .
# We import from tests/ which is a top-level package, so we need
# the actual repo root (parents[3]) on sys.path.
REPO_ROOT = Path(__file__).resolve().parents[3]
if str(REPO_ROOT) not in sys.path:
    sys.path.insert(0, str(REPO_ROOT))

from tests.test_recipe_registry_consistency import (  # noqa: E402
    MULTI_ARCH_DIR,
    classify_domain,
)

# E2E_RESULTS_DIR is a simple top-level path that demos-test computes
# itself (no need to import from the registry test).
E2E_RESULTS_DIR = REPO_ROOT / "e2e-results"
MULTI_ARCH_MASTER = MULTI_ARCH_DIR / "multi-arch-30.yaml"
MULTI_ARCH_TEAMS_DIR = MULTI_ARCH_DIR / "teams"


# ---- Tests ---------------------------------------------------------------

def test_multi_arch_30_master_exists():
    """R110-41: multi-arch-30.yaml must exist (master orchestrator)."""
    assert MULTI_ARCH_MASTER.exists(), (
        f"Missing: {MULTI_ARCH_MASTER}. R110-30 multi-architecture registry."
    )


def test_multi_arch_30_master_has_sub_recipes():
    """R110-41: master orchestrator must declare sub_recipes section."""
    if not MULTI_ARCH_MASTER.exists():
        return
    with open(MULTI_ARCH_MASTER) as f:
        data = yaml.safe_load(f)
    assert data is not None, f"{MULTI_ARCH_MASTER} is empty or invalid YAML"
    sub_recipes = data.get("sub_recipes", [])
    assert len(sub_recipes) >= 6, (
        f"{MULTI_ARCH_MASTER} declares {len(sub_recipes)} sub_recipes, expected 6+ "
        f"(code-review, security-scan, data-quality, perf-eval, refactor, doc-gen)"
    )


def test_multi_arch_30_all_sub_recipe_paths_resolve():
    """R110-41: every sub_recipe.path in master must point to existing file."""
    if not MULTI_ARCH_MASTER.exists():
        return
    with open(MULTI_ARCH_MASTER) as f:
        data = yaml.safe_load(f)
    if data is None:
        return
    missing = []
    for sub in data.get("sub_recipes", []):
        rel = sub.get("path", "")
        if rel.startswith("./"):
            abs_path = (MULTI_ARCH_DIR / rel[2:]).resolve()
        else:
            abs_path = (MULTI_ARCH_DIR / rel).resolve()
        if not abs_path.exists():
            missing.append(str(sub.get("name", "?")) + " -> " + rel)
    assert not missing, (
        f"R110-41: {len(missing)} sub_recipe paths in {MULTI_ARCH_MASTER.name} "
        f"are broken. Missing: {missing}"
    )


def test_multi_arch_30_team_recipes_classified():
    """R110-41: every recipe under multi-arch-30/teams/ is DOMAIN 3 (demo-team)."""
    if not MULTI_ARCH_TEAMS_DIR.exists():
        return
    out = {}
    for p in MULTI_ARCH_TEAMS_DIR.glob("*.yaml"):
        try:
            with open(p) as f:
                data = yaml.safe_load(f)
        except Exception:
            continue
        if isinstance(data, dict):
            out[p.name] = classify_domain(p.name, data, parent_path=p.parent)
    wrong = {k: v for k, v in out.items() if v != "demo-team"}
    assert not wrong, (
        f"R110-41: {len(wrong)}/{len(out)} multi-arch-30/teams/* recipes "
        f"are NOT classified as 'demo-team' (path-based classification broken). "
        f"Wrong: {wrong}"
    )


# ============================================================================
# R110-42: e2e-results wrappers (generated by R110-28 team-composition)
# ============================================================================

def test_e2e_results_directory_exists():
    """R110-42: e2e-results/ must exist (generated by R110-28 team-composition)."""
    assert E2E_RESULTS_DIR.exists(), (
        f"Missing: {E2E_RESULTS_DIR}. R110-42 — e2e-results from team-composition runs."
    )


def test_e2e_results_have_yaml_files():
    """R110-42: e2e-results must contain at least one .yaml file (sanity)."""
    if not E2E_RESULTS_DIR.exists():
        return
    yamls = list(E2E_RESULTS_DIR.rglob("*.yaml"))
    assert len(yamls) > 0, (
        f"R110-42: {E2E_RESULTS_DIR} has no .yaml files. "
        f"Expected team-composition wrappers."
    )


def test_e2e_results_wrappers_valid_yaml():
    """R110-42: every e2e-results wrapper file must be valid YAML."""
    if not E2E_RESULTS_DIR.exists():
        return
    bad = []
    for p in E2E_RESULTS_DIR.rglob("*.yaml"):
        try:
            with open(p) as f:
                data = yaml.safe_load(f)
            if not isinstance(data, dict):
                bad.append((str(p), "not a dict"))
        except Exception as e:
            bad.append((str(p), str(e)[:50]))
    assert not bad, (
        f"R110-42: {len(bad)} e2e-results yaml files are invalid. "
        f"First 5: {bad[:5]}"
    )
