#!/usr/bin/env python3
"""dev_im_design_patches.py — R110-166 phase 2.1 processor for im.finding.created.

Consumed by wf_im_design_patches via dev_mq_consumer.py. Takes a
dev_im_finder_scan result (the im.finding.created payload) and
writes a deterministic, audit-able design-patch to
.mase/im/patches/<request_id>.yaml.

DESIGN PRINCIPLES
  - Idempotent: re-running on the same request_id overwrites the
    patch file (no duplicate designs).
  - Deterministic: same input → same output (no timestamps in
    the patch body itself; only the `generated_at` field).
  - Small: the patch is a structured action-plan, NOT a real
    code-change. The next phase (im-apply) reads the patch and
    applies it.
  - Audit: every patch includes the source request_id, findings
    count by severity, and the top-3 high/blocker findings inline.

The processor's job is DESIGN, not APPLICATION. The apply stage
is a separate workflow that reads the patch and runs sub-agents.
"""
import os
import sys
from pathlib import Path

import yaml

# Re-evaluated at function call time so tests can monkeypatch the
# env var and the directory resolves correctly under isolation.
REPO_ROOT = Path(__file__).resolve().parent.parent
DEFAULT_PATCHES_DIR = REPO_ROOT / ".mase" / "im" / "patches"


def _patches_dir() -> Path:
    """Resolve the patches output directory.

    Default: <repo>/.mase/im/patches (the real install).
    Override: MAS_PATCHES_DIR env var (used by tests so each test
    can write to its own tmp dir without polluting the real one).
    """
    override = os.environ.get("MAS_PATCHES_DIR")
    if override:
        p = Path(override)
    else:
        p = DEFAULT_PATCHES_DIR
    p.mkdir(parents=True, exist_ok=True)
    return p


def process_msg(msg: dict) -> dict:
    """dev_mq_consumer.py entry point. Returns a status dict.

    The msg is the full MQ message dict (with 'msg_id', 'status',
    'payload', 'topic'). The payload comes from dev_im_finder_scan
    --publish, with these keys:
      - request_id, source, timestamp
      - findings_total, findings_by_severity, findings_by_type
      - findings_top (list of {type, severity, location, description},
                       only high/blocker, capped at 20)
    """
    PATCHES_DIR = _patches_dir()

    payload = msg.get("payload", {})
    request_id = payload.get("request_id") or msg.get("msg_id", "unknown")
    findings_total = int(payload.get("findings_total", 0))
    by_severity = dict(payload.get("findings_by_severity") or {})
    by_type = dict(payload.get("findings_by_type") or {})
    findings_top = list(payload.get("findings_top") or [])

    # Decide what kind of patch this is based on findings composition.
    has_blocker = by_severity.get("blocker", 0) > 0
    has_high = by_severity.get("high", 0) > 0
    if has_blocker:
        patch_type = "blocker_remediation"
        priority = "P0"
    elif has_high:
        patch_type = "high_remediation"
        priority = "P1"
    elif findings_total > 0:
        patch_type = "low_medium_cleanup"
        priority = "P2"
    else:
        patch_type = "no_findings"
        priority = "P4"

    # Build per-type actions (3 high/blocker max in the patch body).
    actions = []
    for f in findings_top[:3]:
        actions.append({
            "type": f.get("type", "?"),
            "severity": f.get("severity", "?"),
            "location": f.get("location", "?"),
            "description": f.get("description", ""),
            "action": _suggest_action(f),
        })

    patch = {
        "schema_version": 1,
        "request_id": request_id,
        "source_msg_id": msg.get("msg_id"),
        "source_topic": msg.get("topic"),
        "generated_from": payload.get("source", "unknown"),
        "patch_type": patch_type,
        "priority": priority,
        "findings_total": findings_total,
        "findings_by_severity": by_severity,
        "findings_by_type": by_type,
        "actions": actions,
        "apply_status": "pending",
        "notes": (
            "Auto-generated by dev_im_design_patches.process_msg. "
            "The apply stage should consume this patch and run the "
            "suggested actions via sub-agents. Do not edit the "
            "actions list directly — re-run im-finder instead."
        ),
    }

    out_path = PATCHES_DIR / f"{request_id}.yaml"
    with open(out_path, "w") as f:
        yaml.safe_dump(patch, f, sort_keys=False, default_flow_style=False)

    # Best-effort relative path (use str() if out_path is not under REPO_ROOT,
    # e.g. when MAS_PATCHES_DIR is set to a tmp dir in tests).
    try:
        rel = str(out_path.relative_to(REPO_ROOT))
    except ValueError:
        rel = str(out_path)
    return {
        "patch_written": rel,
        "patch_type": patch_type,
        "priority": priority,
        "actions_count": len(actions),
    }


def _suggest_action(finding: dict) -> str:
    """Map a finding to a concrete action verb (heuristic, deterministic)."""
    ftype = finding.get("type", "")
    if "yaml" in ftype.lower():
        return "fix_yaml_syntax"
    if "secret" in ftype.lower() or "leak" in ftype.lower():
        return "rotate_secret_and_remove_from_history"
    if "drift" in ftype.lower():
        return "align_with_pre_push_validator"
    if "test" in ftype.lower():
        return "add_or_fix_test"
    if "doc" in ftype.lower():
        return "update_documentation"
    return "review_and_manually_fix"


if __name__ == "__main__":
    # Smoke: read stdin as msg-dict, run process_msg
    import json
    msg = json.loads(sys.stdin.read() or "{}")
    result = process_msg(msg)
    print(json.dumps(result, indent=2))
